extension_dir = "ext"
extension = curl
extension = fileinfo
extension = gd
extension = intl
extension = mbstring
extension = mysqli
extension = openssl
extension = pdo_mysql
extension = pdo_sqlite
extension = sqlite3
extension = zip

date.timezone = "Africa/Kampala"
memory_limit = 1024M
upload_max_filesize = 20M
post_max_size = 60M
max_execution_time = 300
