@extends('layouts.app')
@section('title', 'Request a Survey | ATM Uganda')
@section('content')
<section class='page-hero'><div class='shell relative z-10 py-16 sm:py-24'><p class='eyebrow text-yellow-400'>Project intake</p><h1 class='display-title mt-6'>Request a survey.</h1><p class='mt-6 max-w-2xl text-lg leading-8 text-white/70'>Share what you know. We will review the site, scope and timing, then contact you with the best next step.</p></div></section>
<section class='bg-paper py-16 sm:py-24'><div class='shell max-w-4xl'>
    <form method='post' action='{{ route('survey-requests.store') }}' enctype='multipart/form-data' class='grid gap-6 sm:grid-cols-2'>@csrf
        <div class='field'><label for='name'>Your name *</label><input class='input' id='name' name='name' value='{{ old('name') }}' required>@error('name')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='field'><label for='organization'>Organization</label><input class='input' id='organization' name='organization' value='{{ old('organization') }}'></div>
        <div class='field'><label for='email'>Email *</label><input class='input' id='email' type='email' name='email' value='{{ old('email') }}' required>@error('email')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='field'><label for='telephone'>Telephone *</label><input class='input' id='telephone' type='tel' name='telephone' value='{{ old('telephone') }}' required>@error('telephone')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='field'><label for='project_type'>Project type *</label><input class='input' id='project_type' name='project_type' value='{{ old('project_type') }}' placeholder='e.g. subdivision, building, road' required>@error('project_type')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='field'><label for='service_id'>Service</label><select class='input' id='service_id' name='service_id'><option value=''>Help me choose</option>@foreach($services as $service)<option value='{{ $service->id }}' @selected(old('service_id', request('service')) == $service->id)>{{ $service->title }}</option>@endforeach</select></div>
        <div class='field sm:col-span-2'><label for='location'>Site location *</label><textarea class='input min-h-24' id='location' name='location' placeholder='District, town, village, plot reference or nearby landmark' required>{{ old('location') }}</textarea>@error('location')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='field'><label for='latitude'>Latitude</label><input class='input' id='latitude' type='number' step='any' name='latitude' value='{{ old('latitude') }}' placeholder='Optional GPS coordinate'></div>
        <div class='field'><label for='longitude'>Longitude</label><input class='input' id='longitude' type='number' step='any' name='longitude' value='{{ old('longitude') }}' placeholder='Optional GPS coordinate'></div>
        <div class='field sm:col-span-2'><label for='preferred_survey_date'>Preferred survey date</label><input class='input' id='preferred_survey_date' type='date' name='preferred_survey_date' value='{{ old('preferred_survey_date') }}'>@error('preferred_survey_date')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='field sm:col-span-2'><label for='project_description'>Scope and known details *</label><textarea class='input min-h-44' id='project_description' name='project_description' placeholder='Tell us the decision you need to make, site size, available documents and any deadlines.' required>{{ old('project_description') }}</textarea>@error('project_description')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='field sm:col-span-2'><label for='attachments'>Plans, titles or reference files</label><input class='input py-3' id='attachments' type='file' name='attachments[]' multiple accept='.pdf,.jpg,.jpeg,.png,.dwg,.dxf'><p class='text-xs text-ink/50'>Up to 5 files · 10 MB each · PDF, image, DWG or DXF</p>@error('attachments')<p class='error-text'>{{ $message }}</p>@enderror @error('attachments.*')<p class='error-text'>{{ $message }}</p>@enderror</div>
        <div class='sm:col-span-2 flex flex-col gap-4 border-t border-green-950/15 pt-7 sm:flex-row sm:items-center sm:justify-between'><p class='max-w-lg text-xs leading-5 text-ink/50'>By sending this form you allow ATM to use these details to assess and respond to your request.</p><button class='button button-red shrink-0' type='submit'>Send survey request →</button></div>
    </form>
</div></section>
@endsection
