@extends('layouts.app')
@section('title', 'About '.($siteSettings?->company_name ?? 'ATM Surveyors & Engineering Consultants'))
@section('content')
<section class='page-hero'><div class='shell relative z-10 py-20 sm:py-28'><p class='eyebrow text-yellow-400'>About ATM</p><h1 class='display-title mt-6 max-w-5xl'>{{ $siteSettings?->tagline ?? 'Equality for all. Accuracy for every decision.' }}</h1></div></section>
<section class='bg-paper py-20 sm:py-28'><div class='shell grid gap-12 lg:grid-cols-2 lg:gap-24'><div class='reveal'><p class='eyebrow text-green-800'>Our standard</p><h2 class='section-title mt-5 text-green-950'>Professional work, plainly explained.</h2></div><div class='reveal grid gap-6 text-lg leading-8 text-ink/70'><p>{{ $siteSettings?->company_description ?? 'ATM Surveyors & Engineering Consultants supports landowners, developers, institutions and project teams with dependable field data and practical technical advice.' }}</p><p>Our promise—<strong class='text-green-950'>Equality for all</strong>—means every client receives careful attention, transparent communication and work carried out to a professional standard.</p></div></div></section>
<section class='bg-cream py-20 sm:py-28'><div class='shell'><p class='eyebrow text-green-800'>How we work</p><div class='mt-10 grid gap-px bg-green-950/15 md:grid-cols-3'><div class='bg-cream p-8'><span class='text-4xl font-black text-red-600'>01</span><h2 class='mt-6 font-display text-2xl font-black uppercase text-green-950'>Understand</h2><p class='mt-3 text-sm leading-6 text-ink/65'>We clarify the site, purpose, stakeholders and decision the work must support.</p></div><div class='bg-cream p-8'><span class='text-4xl font-black text-red-600'>02</span><h2 class='mt-6 font-display text-2xl font-black uppercase text-green-950'>Measure</h2><p class='mt-3 text-sm leading-6 text-ink/65'>Fieldwork is planned, controlled and checked before conclusions are drawn.</p></div><div class='bg-cream p-8'><span class='text-4xl font-black text-red-600'>03</span><h2 class='mt-6 font-display text-2xl font-black uppercase text-green-950'>Deliver</h2><p class='mt-3 text-sm leading-6 text-ink/65'>You receive clear outputs, practical explanations and responsive follow-through.</p></div></div></div></section>
@if($credentials->isNotEmpty())<section class='bg-green-950 py-20 text-white'><div class='shell'><p class='eyebrow text-yellow-400'>Credentials</p><h2 class='section-title mt-5'>Professional standing</h2><div class='mt-10 grid gap-px bg-white/15 sm:grid-cols-2 lg:grid-cols-3'>@foreach($credentials as $credential)<article class='bg-green-950 p-7'><p class='text-xs font-black uppercase tracking-widest text-yellow-400'>{{ $credential->type }}</p><h3 class='mt-3 text-xl font-black'>{{ $credential->title }}</h3>@if($credential->issuing_body)<p class='mt-2 text-sm text-white/70'>{{ $credential->issuing_body }}</p>@endif @if($credential->registration_number)<p class='mt-3 text-xs text-white/60'>Registration: {{ $credential->registration_number }}</p>@endif</article>@endforeach</div></div></section>@endif
@if($teamMembers->isNotEmpty())<section class='bg-paper py-20'><div class='shell'><h2 class='section-title text-green-950'>Our team</h2><div class='mt-10 grid gap-10 sm:grid-cols-2 lg:grid-cols-3'>@foreach($teamMembers as $member)<article><div class='aspect-[4/3] bg-green-950'>@if($member->photo?->url)<img src='{{ $member->photo->url }}' alt='{{ $member->name }}' class='h-full w-full object-cover'>@endif</div><h3 class='mt-5 text-xl font-black text-green-950'>{{ $member->name }}</h3><p class='text-sm text-red-600'>{{ $member->job_title }}</p></article>@endforeach</div></div></section>@endif
@endsection
